name: SimpleRTP
version: 1.1.0
main: com.simpleplugins.simplertp.SimpleRTP
api-version: '1.21'
author: sardidefcon
description: Simple Random Teleport within a configurable radius

commands:
  rtp:
    description: Teleports the player to a random location.
    usage: /<command>
  srtp:
    description: Reload plugin configuration.
    usage: /<command> reload

permissions:
  srtp.rtp:
    description: Allows using /rtp with no limit
    default: op
  srtp.rtp.once:
    description: Allows using /rtp only once (obsolete if you have srtp.rtp)
    default: false
  srtp.rtp.others:
    description: Allows using /rtp on other players
    default: op
  srtp.reload:
    description: Allows reloading the configuration with /srtp reload
    default: op
